[package]
name = "crate_wide_allow"
version = "2.0.14"
authors = ["Samuel E. Moelius III <sam@moeli.us>"]
description = "A lint to check for `#![allow(...)]` used at the crate level"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[[example]]
name = "ui"
path = "ui/main.rs"

[dependencies]
clippy_utils = { git = "https://github.com/rust-lang/rust-clippy", rev = "e43f5a17d4d9263616ae6fc28a7c5353e80d8a12", optional = true }
if_chain = "1.0.2"

dylint_linting = { path = "../../../utils/linting" }

[target.'cfg(not(no_dev_dependencies))'.dev-dependencies]
assert_cmd = "2.0.6"
cargo_metadata = "0.15.1"

dylint_internal = { path = "../../../internal" }
dylint_testing = { path = "../../../utils/testing" }

[package.metadata.rust-analyzer]
rustc_private = true

[workspace]

[workspace.metadata.dylint]
libraries = [
    { path = "../../*/*" },
]

[features]
default = ["clippy_utils"]
