[package]
name = "overscoped_allow"
version = "2.1.7"
authors = ["Samuel E. Moelius III <sam@moeli.us>"]
description = "A lint to check for `allow` attributes whose scope could be reduced"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[[example]]
name = "ui_general"
path = "ui_general/main.rs"

[[bin]]
name = "ui_test"
path = "ui_test/main.rs"

[dependencies]
anyhow = "1.0"
clippy_utils = { git = "https://github.com/rust-lang/rust-clippy", rev = "991610a9ecb6a9f905238d13ac45613ffe7b7daf" }
if_chain = "1.0"
rustfix = "0.6"
serde = "1.0"
serde_json = "1.0"

dylint_internal = { path = "../../../internal" }
dylint_linting = { path = "../../../utils/linting" }

[dev-dependencies]
assert_cmd = "2.0"
tempfile = "3.4"

dylint_testing = { path = "../../../utils/testing" }

[package.metadata.rust-analyzer]
rustc_private = true

[workspace]

[workspace.metadata.dylint]
libraries = [
    { path = "../../*/*" },
]
