[package]
name = "overscoped_allow"
version = "5.0.0"
authors = ["Samuel E. Moelius III <sam@moeli.us>"]
description = "A lint to check for `allow` attributes whose scope could be reduced"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[[example]]
name = "ui_general"
path = "ui_general/main.rs"

[[bin]]
name = "ui_test"
path = "ui_test/main.rs"

[dependencies]
anyhow = "1.0"
cargo_metadata = "0.23"
clippy_utils = { git = "https://github.com/rust-lang/rust-clippy", rev = "9e3e9649cbae7ed33ba62ca436f43081eaaedeb5" }
once_cell = "1.21"
serde = "1.0"
serde_json = "1.0"

dylint_internal = { path = "../../../internal" }
dylint_linting = { path = "../../../utils/linting" }

[dev-dependencies]
assert_cmd = "2.1"
tempfile = "3.24"

dylint_testing = { path = "../../../utils/testing" }

[lints.rust.unexpected_cfgs]
level = "deny"
check-cfg = ["cfg(dylint_lib, values(any()))"]

[package.metadata.rust-analyzer]
rustc_private = true

[workspace]

[workspace.metadata.dylint]
libraries = [
    { path = "../../general" },
    { path = "../../supplementary" },
    { path = "../../testing/clippy" },
    { path = "../../restriction/*" },
]
