[package]
name = "escaping_doc_link"
version = "5.0.0"
authors = ["Samuel E. Moelius III <sam@moeli.us>"]
description = "A lint to check for doc comment links that escape their packages"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cargo-util = { workspace = true }
cargo_metadata = { workspace = true }
clippy_utils = { workspace = true }
once_cell = { workspace = true }
pulldown-cmark = { workspace = true }

dylint_linting = { path = "../../../utils/linting" }

[dev-dependencies]
dylint_testing = { path = "../../../utils/testing" }

[features]
rlib = ["dylint_linting/constituent"]

[lints]
workspace = true

[package.metadata.rust-analyzer]
rustc_private = true
