[package]
name = "ref_aware_redundant_closure_for_method_calls"
version = "5.0.0"
authors = ["Samuel E. Moelius III <sam@moeli.us>"]
description = "A ref-aware fork of `redundant_closure_for_method_calls`"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[[example]]
name = "eta"
path = "ui/eta.rs"

[[example]]
name = "ref_aware"
path = "ui/ref_aware.rs"

[dependencies]
clippy_utils = { workspace = true }

dylint_internal = { path = "../../../internal" }
dylint_linting = { path = "../../../utils/linting" }

[dev-dependencies]
dylint_testing = { path = "../../../utils/testing" }

[lints]
workspace = true

[package.metadata.rust-analyzer]
rustc_private = true
