[package]
name = "dylint_linting"
version = "2.0.14"
authors = ["Samuel E. Moelius III <sam@moeli.us>"]
description = "Utilities for writing Dylint libraries"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trailofbits/dylint"

[dependencies]
paste = "1.0.9"
rustversion = "1.0.9"
