[package]
name = "dylint_linting"
version = "2.1.1"
authors = ["Samuel E. Moelius III <sam@moeli.us>"]
description = "Utilities for writing Dylint libraries"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trailofbits/dylint"

[dependencies]
cargo_metadata = "0.15.2"
paste = "1.0.9"
rustversion = "1.0.9"
serde = "1.0.150"
thiserror = "1.0.38"
toml = "0.5.10"

dylint_internal = { version = "=2.1.1", path = "../../internal" }

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]

[workspace]

[workspace.metadata.dylint]
libraries = [
    { path = "../../examples/*/*" },
]
