[package]
name = "dylint_linting"
version = "2.1.5"
authors = ["Samuel E. Moelius III <sam@moeli.us>"]
description = "Utilities for writing Dylint libraries"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trailofbits/dylint"

[dependencies]
cargo_metadata = "0.15"
paste = "1.0"
rustversion = "1.0"
serde = "1.0"
thiserror = "1.0"
toml = "0.7"

dylint_internal = { version = "=2.1.5", path = "../../internal" }

[build-dependencies]
toml = "0.7"

[dev-dependencies]
assert_cmd = "2.0"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]

[package.metadata.rust-analyzer]
rustc_private = true

[workspace]

[workspace.metadata.dylint]
libraries = [
    { path = "../../examples/*/*" },
]
