[package]
name = "dylint"
version = "2.1.11"
authors = ["Samuel E. Moelius III <sam@moeli.us>"]
description = "A tool for running Rust lints from dynamic libraries"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trailofbits/dylint"
rust-version = "1.64"

[dependencies]
ansi_term = "0.12"
anyhow = "1.0"
# smoelius: The `cargo` dependency should be kept in sync with dylint/src/toml.rs.
cargo = { version = "0.71", optional = true }
cargo-platform = { version = "0.1", optional = true }
cargo-util = { version = "0.2", optional = true }
cargo_metadata = "0.17"
dirs = "5.0"
glob = { version = "0.3", optional = true }
heck = "0.4"
if_chain = { version = "1.0", optional = true }
is-terminal = "0.4"
log = "0.4"
once_cell = "1.18"
semver = "1.0"
serde = "1.0"
serde_json = "1.0"
tempfile = "3.7"
toml = { version = "0.7", optional = true }
walkdir = "2.3"

dylint_internal = { version = "=2.1.11", path = "../internal", features = ["git", "packaging", "rustup", "sed"] }

[build-dependencies]
dylint_internal = { version = "=2.1.11", path = "../internal", features = ["cargo"] }

[dev-dependencies]
env_logger = "0.10"

dylint_internal = { version = "=2.1.11", path = "../internal", features = ["examples"] }

[features]
default = ["metadata"]
metadata = ["cargo", "cargo-platform", "cargo-util", "glob", "if_chain", "toml"]
package_options = ["if_chain", "dylint_internal/clippy_utils", "dylint_internal/git"]
