[package]
name = "dylint"
version = "2.0.11"
authors = ["Samuel E. Moelius III <sam@moeli.us>"]
description = "A tool for running Rust lints from dynamic libraries"
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trailofbits/dylint"

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0.61"
atty = "0.2.14"
cargo = { version = "0.64.0", optional = true }
cargo-platform = { version = "0.1.2", optional = true }
cargo-util = { version = "0.2.1", optional = true }
cargo_metadata = "0.15.0"
dirs = "4.0.0"
git2 = { version = "0.14.4", optional = true }
glob = { version = "0.3.0", optional = true }
heck = "0.4.0"
if_chain = { version = "1.0.2", optional = true }
lazy_static = "1.4.0"
log = "0.4.17"
once_cell = "1.13.0"
semver = "1.0.13"
serde = "1.0.143"
serde_json = "1.0.83"
tempfile = "3.3.0"
toml_edit = { version = "0.14.4", optional = true }
walkdir = "2.3.2"

dylint_internal = { version = "=2.0.11", path = "../internal", features = ["git", "packaging", "rustup", "sed"] }

[build-dependencies]
dylint_internal = { version = "=2.0.11", path = "../internal", features = ["cargo"] }

[dev-dependencies]
env_logger = "0.9.0"
lazy_static = "1.4.0"
test-log = "0.2.11"

dylint_internal = { version = "=2.0.11", path = "../internal", features = ["examples"] }

[features]
default = ["metadata"]
metadata = ["cargo", "cargo-platform", "cargo-util", "glob", "if_chain", "toml_edit"]
package_options = ["git2", "toml_edit", "dylint_internal/git"]
