[package]
name = "dylint_driver"
version = "0.1.0-pre.10"
authors = ["Samuel E. Moelius III <sam@moeli.us>"]
description = "Dylint driver library"
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trailofbits/dylint"

[dependencies]
anyhow = "1.0.38"
libloading = "0.7.0"
log = "0.4.14"
serde_json = "1.0.64"

dylint_internal = { version = "=0.1.0-pre.10", path = "../internal" }

[workspace]
members = ["."]
