[package]
name = "dylint_driver"
version = "1.0.9"
authors = ["Samuel E. Moelius III <sam@moeli.us>"]
description = "Dylint driver library"
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trailofbits/dylint"

[dependencies]
anyhow = "1.0.51"
libloading = "0.7.2"
log = "0.4.14"
serde_json = "1.0.73"

dylint_internal = { version = "=1.0.9", path = "../internal" }

[workspace]

[workspace.metadata.dylint]
libraries = [
    { path = "../examples/*" },
]
