[package]
name = "dylint_driver"
version = "2.0.13"
authors = ["Samuel E. Moelius III <sam@moeli.us>"]
description = "Dylint driver library"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trailofbits/dylint"

[dependencies]
anyhow = "1.0.65"
libloading = "0.7.3"
log = "0.4.17"
rustversion = "1.0.9"
serde_json = "1.0.87"

dylint_internal = { version = "=2.0.13", path = "../internal", features = ["rustup"] }

[workspace]

[workspace.metadata.dylint]
libraries = [
    { path = "../examples/*/*" },
]
