[package]
name = "dylint-link"
version = "2.0.5"
authors = ["Samuel E. Moelius III <sam@moeli.us>"]
description = "A wrapper around Rust's default linker to help create Dyling libraries"
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trailofbits/dylint"

[dependencies]
anyhow = "1.0.57"
dirs = "4.0.0"
env_logger = "0.9.0"
if_chain = "1.0.2"
toml_edit = "0.14.4"

dylint_internal = { version = "=2.0.5", path = "../internal" }

[build-dependencies]
dylint_internal = { version = "=2.0.5", path = "../internal" }

[dev-dependencies]
assert_cmd = "2.0.4"
curl = "0.4.43"
predicates = "2.1.1"
tempfile = "3.3.0"
test-log = "0.2.10"

dylint_internal = { version = "=2.0.5", path = "../internal", features = ["git2"] }

[target.'cfg(target_os = "windows")'.dependencies]
cc = "1.0.73"
