[package]
name = "nonexistent_path_in_comment"
version = "5.0.0"
authors = ["Augustin Villetard"]
description = "Lint for nonexistent paths in comments"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cargo_metadata = { workspace = true }
clippy_utils = { workspace = true }
dylint_linting = { path = "../../../utils/linting" }
regex = { workspace = true }

[dev-dependencies]
dylint_testing = { path = "../../../utils/testing" }

[features]
rlib = ["dylint_linting/constituent"]

[lints]
workspace = true

[package.metadata.rust-analyzer]
rustc_private = true
