[package]
name = "nonexistent_path_in_comment"
version = "4.0.0"
authors = ["Augustin Villetard"]
description = "Lint for nonexistent paths in comments"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cargo_metadata = { workspace = true }
clippy_utils = { git = "https://github.com/rust-lang/rust-clippy", rev = "19e305bb57a7595f2a8d81f521c0dd8bf854e739" }
dylint_linting = { path = "../../../utils/linting" }
once_cell = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
dylint_testing = { path = "../../../utils/testing" }

[features]
rlib = ["dylint_linting/constituent"]

[lints]
workspace = true

[package.metadata.rust-analyzer]
rustc_private = true
