[package]
name = "dylint_testing"
version = "5.0.0"
authors = ["Samuel E. Moelius III <sam@moeli.us>"]
description = "Utilities for testing Dylint libraries"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trailofbits/dylint"

[dependencies]
anyhow = { workspace = true }
cargo_metadata = { workspace = true }
compiletest_rs = { workspace = true }
env_logger = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }

dylint = { version = "=5.0.0", path = "../../dylint" }
dylint_internal = { version = "=5.0.0", path = "../../internal" }

[features]
default = []
deny_warnings = []

[lints]
workspace = true
