[package]
name = "dylint_testing"
version = "1.0.4"
authors = ["Samuel E. Moelius III <sam@moeli.us>"]
description = "Utilities for testing Dylint libraries"
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trailofbits/dylint"

[dependencies]
anyhow = "1.0.44"
cargo_metadata = "0.14.0"
compiletest_rs = "0.7.0"
env_logger = "0.9.0"
lazy_static = "1.4.0"
log = "0.4.14"
regex = "1.5.4"
serde_json = "1.0.68"
tempfile = "3.2.0"

dylint = { version = "=1.0.4", path = "../../dylint", default-features = false }
dylint_internal = { version = "=1.0.4", path = "../../internal" }

[features]
default = []
dylint_driver_local = ["dylint/dylint_driver_local"]
