[package]
name = "dylint_testing"
version = "2.0.0"
authors = ["Samuel E. Moelius III <sam@moeli.us>"]
description = "Utilities for testing Dylint libraries"
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/trailofbits/dylint"

[dependencies]
anyhow = "1.0.57"
cargo_metadata = "0.14.2"
compiletest_rs = "0.7.1"
env_logger = "0.9.0"
lazy_static = "1.4.0"
log = "0.4.16"
once_cell = "1.10.0"
regex = "1.5.5"
serde_json = "1.0.79"
tempfile = "3.3.0"

dylint = { version = "=2.0.0", path = "../../dylint", default-features = false }
dylint_internal = { version = "=2.0.0", path = "../../internal" }

[features]
default = []
dylint_driver_local = ["dylint/dylint_driver_local"]
