name: Upgrade examples

# smoelius: Every Saturday at 3:00 UTC (Friday at 22:00 EST), create a PR to update the example
# libraries to the latest version of `clippy_utils`.

on:
  schedule:
    - cron: 0 3 * * sat
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  upgrade:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v6

      - name: Rustup
        run: rustup update

      - name: Install dylint-link
        run: cargo install --path ./dylint-link --force

      - name: Upgrade examples
        run: |
          scripts/upgrade_examples.sh
          git diff --name-only

      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Upgrade examples
          branch: upgrade-examples
          branch-suffix: random
          commit-message: Upgrade examples
          token: ${{ github.token }}
